# This file is auto-generated by the `evennia connections` wizard.
# Don't edit manually, your changes will be overwritten.

GAME_INDEX_ENABLED = True
GAME_INDEX_LISTING = \
{   'game_name': "Crypt Crawlin' Kitties",
    'game_status': 'pre-alpha',
    'game_website': '',
    'listing_contact': 'sw26@icsd.k12.ny.us',
    'long_description': "Crypt crawlin' kitties is a game set in Rathkar, a "
                        'planet created by Gideon nightcatcher. There are many '
                        'dungeons hidden beneath the surface, and there are '
                        'hidden magic words to discover, all inspired by old '
                        'games.',
    'short_description': 'Crypt crawlin kitties(or cck) is a text game set in '
                         'the world of rathkar, with a main continent and an '
                         'island.',
    'telnet_hostname': '',
    'telnet_port': '',
    'web_client_url': ''}